version: '3.8'

services:

  identity_database:
    build:
      context: ./src/db/identity/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  identity_server:
    build:
      context: ./src/server/identity/expressjs
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - identity_database

  post_database:
    build:
      context: ./src/db/post/elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin=/.*/
      - http.cors.enabled=true
    ports:
      - 9200:9200

  post_server:
    build:
      context: ./src/server/post/expressjs
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 3002
    ports:
      - 3002:3002
    depends_on:
      - identity_server
      - post_database

  web_client:
    build:
      context: ./src/client/web/angular
      dockerfile: Dockerfile
    environment:
      IDENTITY_SERVER: http://localhost:3001
      POST_SERVER: http://localhost:3002
    ports:
      - 3000:80
    depends_on:
      - identity_server
      - post_server
